#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Update 'hosts' file with dn-ip predefinitions
hosts_config="/etc/hosts"
echo "127.0.0.1       localhost localhost.localdomain" >> $hosts_config
