#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Set 'bash' as default shell for 'manila' user.
id manila 2>/dev/null || useradd -m manila -s /bin/bash
echo manila:manila | chpasswd
