#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Add useful config options for vim config
vim_config="/etc/vim/vimrc"
echo "set hls is" >> $vim_config
echo "set tabstop=4" >> $vim_config
echo "set shiftwidth=4" >> $vim_config
echo "set expandtab" >> $vim_config
echo "set nu" >> $vim_config
echo "set background=dark" >> $vim_config
echo "set cc=80" >> $vim_config
