#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

useradd -m ${DIB_MANILA_USER_USERNAME}
set +x
if [ -n "${DIB_MANILA_USER_PASSWORD}" ]; then
    echo "Setting password."
    echo "${DIB_MANILA_USER_USERNAME}:${DIB_MANILA_USER_PASSWORD}" | chpasswd
fi
set -x

cat > /etc/sudoers.d/${DIB_MANILA_USER_USERNAME} << EOF
${DIB_MANILA_USER_USERNAME} ALL=(ALL) NOPASSWD:ALL
EOF
chmod 0440 /etc/sudoers.d/${DIB_MANILA_USER_USERNAME}
visudo -c || rm /etc/sudoers.d/${DIB_MANILA_USER_USERNAME}


if [ -f /tmp/in_target.d/devuser-ssh-authorized-keys ]; then
    mkdir -p /home/${DIB_MANILA_USER_USERNAME}/.ssh
    cp /tmp/in_target.d/manilauser-ssh-authorized-keys /home/${DIB_MANILA_USER_USERNAME}/.ssh/authorized_keys
fi

chown -R ${DIB_MANILA_USER_USERNAME}:${DIB_MANILA_USER_USERNAME} /home/${DIB_MANILA_USER_USERNAME}
