#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

# Install required packages
install-packages git-core cmake build-essential libkrb5-dev bison flex

# Build nfs-ganesha
cd /usr/src
# TODO(u_glide): Move branch to config option through "environment.d"
git config --global http.sslVerify false
git clone --depth 5 --recursive -b "V2.2-stable" \
    https://github.com/nfs-ganesha/nfs-ganesha.git
cd nfs-ganesha
mkdir build && cd build
cmake ../src && make

# Install nfs-ganesha
sudo make install

# (aovchinnikov): This will be used later on when all peculiarities of
# running ganesha inside a container are sorted out.
#sudo cp ../src/scripts/ganeshactl/org.ganesha.nfsd.conf /etc/dbus-1/system.d/
#install -D -g root -o root -m 0755 \
#    ${SCRIPTDIR}/nfs-ganesha /etc/init.d/nfs-ganesha
#sudo update-rc.d nfs-ganesha defaults

# Remove sources
cd /usr/src && rm -fR nfs-ganesha
