#!/bin/bash -xe

MANILA_DOCKER_CONTAINER_NAME=${MANILA_DOCKER_CONTAINER_NAME:-"manila-docker-container"}
MANILA_DOCKER_CONTAINER_IMAGE_NAME=${MANILA_DOCKER_CONTAINER_IMAGE_NAME:-"$MANILA_DOCKER_CONTAINER_NAME.tar"}

sudo podman build -t "$MANILA_DOCKER_CONTAINER_NAME" data/docker
sudo podman save -o "$MANILA_DOCKER_CONTAINER_IMAGE_NAME" "$MANILA_DOCKER_CONTAINER_NAME"
sudo gzip -v --force "$MANILA_DOCKER_CONTAINER_IMAGE_NAME"
