#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Enable registry in samba config
sed -i "s/\[global\]/\[global\]\\n\\n   include = registry\\n/g" /etc/samba/smb.conf